image: golang:latest

stages:
    - lint
    - build

format:
    stage: lint
    script:
        - make lint

compile:
    stage: build
    script:
        - make build
    artifacts:
        paths:
            - wallabako
