image: golang:latest

stages:
    - lint
    - build

format:
    stage: lint
    script:
        - go get github.com/golang/lint/golint
        - make lint

compile:
    stage: build
    script:
        - go get github.com/Strubbl/wallabago
        - make build GOARCH=arm BINARY=wallabako.arm
        - make build BINARY=wallabako.$(arch)
    artifacts:
        untracked: true
        when: always
