image: golang:latest

stages:
    - lint
    - build

format:
    stage: lint
    script:
        - go get github.com/golang/lint/golint
        - make lint

compile:
    stage: build
    script:
        - GOARM=7 GOARCH=arm make clean build
        - mv wallabako wallabako.arm7
        - make build
    artifacts:
        paths:
            - wallabako
