#!/bin/sh

# cargo-culted from
# https://github.com/Michael-Bell/Kobo-Mini-Wireless-Sync/blob/master/update.sh

# unfortunately, this still requires user interaction. see a more
# complete discussion here:
# https://www.mobileread.com/forums/showthread.php?p=3467503

echo Simulating USB cable connect
echo usb plug add >>/tmp/nickel-hardware-status
echo Waiting 30 seconds for user to hit Connect
sleep 30
echo Simulating USB cable disconnect
echo usb plug remove >>/tmp/nickel-hardware-status
