#!/bin/sh
set -eu

# Build the two disk images and boot artifacts consumed by vm_test.go.
#
# This script runs entirely on the host. Docker is used as a reproducible
# root-filesystem builder and exporter; Docker is not installed in the guest
# and Readeck does not run in this image.
#
# Inputs:
#   OUTPUT_DIR      Destination for the kernel, initramfs, and disk images.
#   SSH_PUBLIC_KEY  Ephemeral public key generated by the calling Go test.
#
# Outputs:
#   vmlinuz-virt    Alpine's ARMv7 virt kernel.
#   initramfs-virt  Matching Alpine initramfs.
#   root.ext4       Writable Alpine root filesystem.
#   onboard.fat     Empty FAT32 volume mounted as /mnt/onboard in the guest.
#
# set -e stops on the first failed build step. set -u catches misspelled or
# missing shell variables before they can produce an incomplete disk image.

# Keep the interface intentionally small: all other behavior is fixed by the
# checked-in Dockerfile and testvm files.
if [ "$#" -ne 2 ]; then
	echo "usage: $0 OUTPUT_DIR SSH_PUBLIC_KEY" >&2
	exit 2
fi

# Use ordinary shell variables rather than resolving paths here. The caller
# supplies paths in its own temporary directory, and every use below is quoted.
output_dir=$1
public_key=$2

# Pin the local tag to the Alpine release in testvm/Dockerfile. It is only a
# build/cache identifier and is never pushed by this script.
image_tag=kobodeck-testvm-rootfs:alpine-3.24.1-armv7

# CI may point this at an actions/cache-managed directory. An empty value means
# "use Docker's normal layer cache only."
cache_dir=${KOBODECK_VM_CACHE_DIR:-}

# Fail before creating temporary state if a required host utility is missing.
# QEMU, SSH, and ssh-keygen are checked by the Go test because this script does
# not invoke them directly.
for command in docker mkfs.ext4 mkfs.vfat truncate; do
	if ! command -v "$command" >/dev/null 2>&1; then
		echo "missing required command: $command" >&2
		exit 1
	fi
done

# Stage the exported container filesystem in a private temporary directory.
# The final images go to output_dir; the unpacked tree never needs to persist.
mkdir -p "$output_dir"
rootfs_dir=$(mktemp -d)
container_id=

# docker create produces a stopped container solely for `docker export`. Remove
# it and the staging tree on success, failure, or interruption. Cleanup is best
# effort so it cannot hide the original build error.
cleanup() {
	if [ -n "$container_id" ]; then
		docker rm -f "$container_id" >/dev/null 2>&1 || true
	fi
	rm -rf "$rootfs_dir"
}
trap cleanup EXIT INT TERM

# Loading a saved image avoids rebuilding/emulating Alpine package installation
# on every CI run. docker build still runs afterward so Docker can validate the
# current Dockerfile/context and reuse or refresh layers as needed.
if [ -n "$cache_dir" ] && [ -f "$cache_dir/rootfs-image.tar" ]; then
	docker load --input "$cache_dir/rootfs-image.tar" >/dev/null
fi

# Build explicitly for linux/arm/v7. On an x86 host Docker uses the binfmt/QEMU
# support installed by CI to execute Dockerfile RUN steps for that platform.
docker build --platform linux/arm/v7 --tag "$image_tag" testvm

# Save the completed builder image rather than the expanded ext4 file. The
# Docker image compresses and caches more effectively, while root.ext4 is cheap
# to regenerate from it.
if [ -n "$cache_dir" ]; then
	mkdir -p "$cache_dir"
	docker save --output "$cache_dir/rootfs-image.tar" "$image_tag"
fi

# Export a plain root filesystem without Docker overlay metadata. --no-same-owner
# is essential for rootless/non-root test runs: the host user generally cannot
# recreate root ownership while unpacking. The guest init repairs the one
# ownership-sensitive OpenSSH directory before starting sshd.
container_id=$(docker create "$image_tag")
docker export "$container_id" | tar --no-same-owner -xf - -C "$rootfs_dir"

# mkfs.ext4 populates the image as the host user and must be able to read every
# staged path. Alpine contains execute-only helpers such as /bin/bbsuid, so
# normalize only the staging user's read/traverse bits. Do not broaden group or
# world permissions in the guest image.
find "$rootfs_dir" -type d -exec chmod u+rx {} +
find "$rootfs_dir" -type f -exec chmod u+r {} +

# Authorize the ephemeral key before creating root.ext4. Password authentication
# is disabled in sshd_config, making this key the only guest control credential.
mkdir -p "$rootfs_dir/root/.ssh"
cp "$public_key" "$rootfs_dir/root/.ssh/authorized_keys"
chmod 0600 "$rootfs_dir/root/.ssh/authorized_keys"

# linux-virt installs versioned boot files behind these stable names. Locate the
# first matching pair and fail clearly if Alpine changes its package layout.
kernel=$(find "$rootfs_dir/boot" -maxdepth 1 -name 'vmlinuz-virt' -print -quit)
initramfs=$(find "$rootfs_dir/boot" -maxdepth 1 -name 'initramfs-virt' -print -quit)
if [ -z "$kernel" ] || [ -z "$initramfs" ]; then
	echo "Alpine linux-virt did not provide a kernel and initramfs" >&2
	exit 1
fi
cp "$kernel" "$output_dir/vmlinuz-virt"
cp "$initramfs" "$output_dir/initramfs-virt"

# Create a raw, unpartitioned ext4 filesystem and populate it directly from the
# staged Alpine tree. QEMU exposes this as /dev/vda; no partition table or boot
# loader is needed because vm_test.go supplies the kernel and initramfs.
#
# 512 MiB keeps the image small while leaving room for package installation and
# future Kobodeck test artifacts.
truncate -s 512M "$output_dir/root.ext4"
mkfs.ext4 -q -F -d "$rootfs_dir" "$output_dir/root.ext4"

# Model the Kobo's user-visible onboard storage as a separate FAT32 block
# device. It is intentionally empty for the connectivity smoke test and is
# mounted at /mnt/onboard by the guest init script.
truncate -s 64M "$output_dir/onboard.fat"
mkfs.vfat "$output_dir/onboard.fat" >/dev/null
