#!/bin/sh
set -eu

mount -o remount,rw /

mountpoint -q /dev || mount -t devtmpfs devtmpfs /dev
mkdir -p /dev/pts /run /tmp /mnt/onboard
mountpoint -q /dev/pts || mount -t devpts devpts /dev/pts
mountpoint -q /proc || mount -t proc proc /proc
mountpoint -q /sys || mount -t sysfs sysfs /sys
mountpoint -q /run || mount -t tmpfs tmpfs /run
mountpoint -q /tmp || mount -t tmpfs tmpfs /tmp
mkdir -p /run/udev

mount -t vfat /dev/vdb /mnt/onboard

/sbin/udevd --daemon
udevadm trigger --type=subsystems --action=add
udevadm trigger --type=devices --action=add
udevadm settle

ip link set lo up
ip link set eth0 up
udhcpc -q -n -t 10 -i eth0

chown root:root /var/empty
/usr/sbin/sshd
echo "KOBODECK_TESTVM_READY" >/dev/ttyAMA0

while :; do
	sleep 3600
done
